### ISSUE TITLE
Hi, I'd like to request the option to pin app but still be able to touch with unfrozen screen

### ISSUE THREAD

**Issue by grubbybrick** [kofuk/SecureScreen#2]
I'm a mobile gamer and I mainly using 4 claws fingers which will looked like this: https://www.youtube.com/watch?v=W2NVEIE-zXI

As you can see the way I play my games with 4 fingers which is prone to accidentally swipe down the notification bar during gameplay and most of the time this will ruin my game. There is a fix for that by enabling screen pinning options: https://www.youtube.com/watch?v=UnWjgXV6-9Q

However, for xiaomi - miui phone in general, the company has disabled this option on all of their newer phones released post 2020 , even setedit can't fix it. I almost gave up then came across your app. Your app can actually pin the app but the screen would freeze and i couldn't touch anything (i suppose this is a feature).

I believe by giving an option to just pinning the app alone without blocking touch and freezing the screen could be a great solution for Xiaomi phone users in the long run. Since many users have the same problem as me and they still can't find a fix yet (https://www.youtube.com/watch?v=ZjG194DY49A) <- solution which only work with 2019 and early 2020 xiaomi phones, u can check the comment to find those users who are struggling.

**Comment by kofuk** [comment]
I understood the necessity of the functionality.

Unfortunately, It's probably impossible for this app to pin *another app*.
This app is implemented by pinning a completely transparent screen, which is owned by this app, so technically this app pins *my app* rather than other apps.

Alternatively, you may be able to pin arbitrary apps by connecting your phone to your computer.

```
$ adb shell am task lock <your app's task id here>
```

https://android.stackexchange.com/questions/118731/how-do-i-screen-pin-an-app-in-android-lollipop-using-command-line
